Add conversion to PEM
dracut-crypt-ssh/dracut-crypt-ssh pull request #55
Opened 2022-02-27 14:18 UTC by pathetic-lynx

Detect when the key files are not in PEM format and convert them if necessary

2022-02-27 14:21 UTC, pathetic-lynx commented
I can confirm this works for rsa, ecdsa and ed25519.
The detection with grep seems a little sketchy to me, not sure if this always correct.

2023-01-18 16:25 UTC, ahesford requested changes

2023-01-18 16:25 UTC, ahesford commented on modules/60crypt-ssh/module-setup.sh
> +    }
Eventually, the entire key-handling portion should be reworked. OpenSSH keys should be a fallback, not the fundamental currency of this module. The SYSTEM option is a bad idea and should be de-emphasized or removed entirely. Generated keys should persist between runs (or at least a configuration option should allow this).

In the meantime, the multiple nesting of Boolean operators is a bit hard to parse, and let's make the header parsing a bit stricter.

```suggestion
    if ! head -n1 "${osshKey}" | grep -q -- "-----BEGIN ${msgKeyType} PRIVATE KEY-----"; then
      dinfo "Converting ${osshKey} to PEM format"
      ssh-keygen -q -e -p -P "" -N "" -m pem -f ${osshKey} > /dev/null 2>&1 || \
        derror "Converting ${osshKey} to PEM format failed"
    fi
```

2024-01-31 12:44 UTC, ahesford commented
Closing due to inactivity

2024-01-31 12:44 UTC, closed without merging