Fix permission of dropbear_acl before install
dracut-crypt-ssh/dracut-crypt-ssh pull request #79
Opened 2024-11-20 02:55 UTC by yookoala

* Fix the ownership and permission of the dropbear_acl before installing using dracut.
* Fixes #78.

2024-11-20 06:20 UTC, ahesford commented
This should just fix the permissions on the target file directly, rather than making an intermediate copy that isn't cleaned up.

2024-11-20 09:54 UTC, yookoala commented
> This should just fix the permissions on the target file directly, rather than making an intermediate copy that isn't cleaned up.

The intermediate copy is created in the `$tmpDir` so it is cleaned up OK.

With sudoer setup, usually the `authorized_keys` file with the sudoer account has all the keys that are supposed to be accessible to the account with ssh. I set it to the `dropbear_acl` target file because I do not want to keep 2 version of the file and simply want to reuse it.

If I set the file to be owned by root, then ssh won't be login to the regular user. I think forcing `dropbear_acl` to have the same permission as the supposed `/root/.ssh/authorized_keys` is not the proper solution here.

2024-11-20 11:30 UTC, ahesford commented
I'm not telling you to change the permissions of the source file, but to adjust the permissions of the destination *after it's copied*.

2024-11-20 13:14 UTC, yookoala commented
> I'm not telling you to change the permissions of the source file, but to adjust the permissions of the destination _after it's copied_.

I'm sorry but I'm not familiar with dracut enough to do this. [dracut.modules](https://www.man7.org/linux/man-pages/man7/dracut.modules.7.html) documentation does not provide a command / function to change a file's permission or ownership after `inst`.

Please advice how it should be done. Thanks a lot.

2024-11-20 15:06 UTC, zdykstra commented
> > I'm not telling you to change the permissions of the source file, but to adjust the permissions of the destination _after it's copied_.
> 
> I'm sorry but I'm not familiar with dracut enough to do this. [dracut.modules](https://www.man7.org/linux/man-pages/man7/dracut.modules.7.html) documentation does not provide a command / function to change a file's permission or ownership after `inst`.
> 
> Please advice how it should be done. Thanks a lot.

Files installed in the initramfs are available at `${initdir}/their/installed/path`, so in this case it'd be `${initdir}/root/.ssh/authorized_keys` .

2024-11-20 15:11 UTC, yookoala commented
@zdykstra: Thanks! Updated.

2024-12-03 07:16 UTC, yookoala commented
@ahesford: I've already updated according to your previous comment. Is there anything still needed to change in this PR before merge?

2024-12-03 12:48 UTC, ahesford requested changes

2024-12-03 12:48 UTC, ahesford commented on modules/60crypt-ssh/module-setup.sh
> +  chown root:root ${initdir}/root/.ssh/authorized_keys
It's better to use `0:0` instead of `root:root` here, in case some weird environment doesn't map `root` to uid 0.

2024-12-03 12:51 UTC, yookoala commented
@ahesford: Done. Please check.

2024-12-03 12:55 UTC, merged